name: MicroPing
main: xyz.mrcote33.ping.MicroPing
author: MrCote33
version: "0.4.2"
api-version: "1.16"
description: "MicroPing is minimalist and modificated version of SpigotPing."
commands:
    pingreload:
      description: Reloads the plugin.
