name: MicroPing
main: xyz.mrcote33.ping.MicroPing
author: MrCote33
version: "1.0.0"
api-version: "1.17"
description: "MicroPing is minimalist and modificated version of SpigotPing."
softdepend: [PlaceholderAPI]
commands:
    pingreload:
      description: Reloads the plugin.
